= Shapeless: Introduction resources

:published_at: 2016-09-05
:hp-tags: shapeless

== Where to start if you want to learn shapeless

Recently I decided to have a better look at https://github.com/milessabin/shapeless[shapeless], the generic programming library for Scala. In the previous couple of years I had bookmarked several links and have recently read all of them. In this blog post I present the most useful ones for someone who want to be introduced to the library.

The following blog posts are introductory to shapeless. Basically they are a smooth introduction to shapeless, something to warm up

* https://jto.github.io/articles/getting-started-with-shapeless/[Getting started with Shapeless] by https://twitter.com/skaalf[Julien Tournay] (heterogenous lists, polymorphic function values, generic, tuples, lenses)
* https://enear.github.io/2016/04/05/bits-shapeless-1-hlists/[Bits of Shapeless part 1: HLists] by https://twitter.com/ragb[Rui Batista] (Heterogenous lists)

Also these slides on http://slick.lightbend.com/talks/scalaio2014/Type-Level_Computations.pdf[Type-Level Computations in Scala] by https://twitter.com/StefanZeiger[Stefan Zeiger] (not shapeless per se , but a lot of examples for type-level scala, like type-level booleans, type-level natural numbers, translation to types, recursion with types, type functions, type lambdas, heterogenous lists, hlist fold). I tried to find the video talk, but couldn’t find it online.

The https://rnduja.github.io/2016/01/19/a_shapeless_primer/[Α shapeless primer] blog post by https://twitter.com/evacchi[Edoardo Vacchi] is the best and most complete introductory blog post I could find. It really goes into a lot of explaining hlists, product types, Generic[T], FnToProduct[F] object, implicit value resolution, evidences and typeclasses, the Aux Pattern). There is also a https://rnduja.github.io/2015/10/07/scala-dependent-types/[video] presentation by the author Edoardo Vacchi https://speakerdeck.com/evacchi/be-like-water-scala-italy-2016[(with slides)]. In this blog post I find very interesting the comparison of Scala with Prolog and how implicit variables, implicit functions, type parameters in functions and implicit parameter lists of functions can be “interpreted” in a rule-based context.





